version: "3"

services:
  mysqldb:
    image: mysql:5.7
    container_name: mysqldb
    environment:
      - MYSQL_DATABASE=testdb
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_ROOT_HOST=%
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    ports:
      - 3306:3306
    networks:
      - network-tier
    platform: linux/amd64

  backend:
    container_name: backend
    volumes:
      - ./backend:/backend
    build: ./backend
    depends_on:
      - mysqldb
    ports:
      - 8080:8080
    networks:
      - network-tier

networks:
    network-tier:
