version: "3"

services:
  backend:
    container_name: prac-backend
    build: ./backend
    restart: on-failure
    depends_on:
      - mysqldb
    ports:
      - '8080:8080'
    environment:
      spring.datasource.url: "jdbc:mysql://prac-mysqldb:3306/prac_db?useSSL=false&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&autoReconnect=true&createDatabaseIfNotExist=true"
    volumes:
      - ./backend:/backend
    networks:
      - network-tier
    tty: true

  mysqldb:
    image: mysql:5.7
    container_name: prac-mysqldb
    env_file:
      - "./.env"
    command:
      [
          "--character-set-server=utf8mb4",
          "--collation-server=utf8mb4_unicode_ci",
      ]
    volumes:
      - mysql-data:/var/lib/prac
    ports:
      - "3306:3306"

    networks:
      - network-tier
    platform: linux/amd64

networks:
  network-tier:
    external: true

volumes:
  mysql-data:
